---
openapi: '3.0.0'
info:
  title: 'Jackpot'
  version: '1.0.0'
  description: 'Jackpot'
servers:
  - url: ''
tags:
  - name: User
  - name: Ticket
  - name: Jackpot
  - name: Revenue
  - name: PurchaseHistory
paths:
  #-----------USER--------------------------------------------------------------------------------------------------------------------------------
  /users:
    get:
      tags:
        - 'User'
      summary: get user information.
      responses:
        200:
          description: 'Successful operation'

  /users/connect-wallet:
    post:
      tags:
        - 'User'
      summary: user connect wallet.
      responses:
        200:
          description: 'Successful operation'

  /users/{userId}:
    get:
      tags:
        - 'User'
      summary: get user information.
      responses:
        200:
          description: 'Successful operation'

  /users/{userId}/purchase-histories:
    get:
      tags:
        - 'User'
      summary: get user information.
      responses:
        200:
          description: 'Successful operation'

  #-----------TICKET--------------------------------------------------------------------------------------------------------------------------------
  /tickets:
    post:
      tags:
        - 'Ticket'
      summary: User connect wallet.
      responses:
        200:
          description: 'Successful operation'
    get:
      tags:
        - 'Ticket'
      summary: User connect wallet.
      responses:
        200:
          description: 'Successful operation'

  #-----------JACKPOT-------------------------------------------------------------------------------------------------------------------------------
  /jackpots:
    post:
      tags:
        - 'Jackpot'
      summary: User connect wallet.
      responses:
        200:
          description: 'Successful operation'
  #-----------REVENUE-------------------------------------------------------------------------------------------------------------------------------
  /revenue:
    post:
      tags:
        - 'Revenue'
      summary: User connect wallet.
      responses:
        200:
          description: 'Successful operation'
  #-----------PURCHASE-HISTORY----------------------------------------------------------------------------------------------------------------------
  /purchase-histories:
    post:
      tags:
        - 'PurchaseHistory'
      summary: User connect wallet.
      responses:
        200:
          description: 'Successful operation'

externalDocs:
  description: 'More details'
  url: 'http://swagger.io'
